# Generated by Django 5.2.7 on 2025-10-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi_singkat', models.TextField(help_text='Paragraf singkat untuk di homepage')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('deskripsi_lengkap', models.TextField(help_text="Deskripsi untuk halaman 'About'")),
                ('visi', models.TextField(blank=True)),
                ('misi', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('gambar_thumbnail', models.ImageField(upload_to='projects/')),
                ('link_demo', models.URLField(blank=True)),
                ('link_repo', models.URLField(blank=True)),
                ('skills', models.ManyToManyField(blank=True, to='api.skill')),
                ('tools', models.ManyToManyField(blank=True, to='api.tool')),
            ],
        ),
    ]
